server:
  port: 8081

# debug: true

########################################################
#  Setup for Spring Boot 1.5.10 Database Configuration
########################################################
# MySql Database Configuration (primary)
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/hr_config
#     driver-class-name: com.mysql.jdbc.Driver
#     username: ENC(zhLCNPd/bXuun8zzoJ+kXA==)
#     password: ENC(e3tq2eKMAjyaIF7zKGlWJABKFwNeXOmB)
#   jpa:
#     database: default

# Oracle Database Configuration
# oracle:
#   datasource:
#     url: jdbc:oracle:thin:@//localhost:1521/xe
#     driver-class-name: oracle.jdbc.OracleDriver
#     username: ENC(XvehGtnHK2RxubvlHOMuIg==)
#     password: ENC(FnDeid1/sI5zEIAi1sggdqJaZsOH0Brl)
    

########################################################
#  Setup for Spring Boot 2.0.1 Database Configuration
########################################################
# MySql Database Configuration (primary)
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/hr_config
      username: ENC(zhLCNPd/bXuun8zzoJ+kXA==)
      password: ENC(e3tq2eKMAjyaIF7zKGlWJABKFwNeXOmB)

# Oracle Database Configuration
oracle:
  datasource:
    hikari:
      jdbc-url: jdbc:oracle:thin:@//localhost:1521/xe
      username: ENC(XvehGtnHK2RxubvlHOMuIg==)
      password: ENC(FnDeid1/sI5zEIAi1sggdqJaZsOH0Brl)